[workspace]
members = [
  "rair-env",
  "rair-io",
  "rtrees",
  "test_file",
]

[package]
name = "rcore"
version = "0.1.0"
authors = ["oddcoder <ahmedsoliman@oddcoder.com>"]
license = "LGPL-3.0-or-later"
repository = "https://github.com/oddcoder/rair"
keywords = ["Rair", "Core"]
description = "Core module for Rair"
categories = ["cli"]
readme = "readme.md"

[dependencies]
flate2 = "1.0"
rair-env = {path = "rair-env"}
rair-io = {path = "rair-io"}
rtrees = {path = "rtrees"}
serde = { version = "1.0", features = ["derive"]}
serde_cbor = "0.10"
yansi = "0.5"

[dev-dependencies]
test_file = {path = "test_file"}
